#!/bin/sh

DATE=`date "+%Y-%m-%d"`

if [ "x$1" = "x" ]; then
  echo "Usage: $0 <version number>"
  exit 1
fi

sed -i -e 's/^VERSION=.*$/VERSION='$1'/g'    Makefile
sed -i -e 's/^RELEASE=.*$/RELEASE='$DATE'/g' Makefile

sed -i -e 's/^Version:.*$/Version: '$1'/g'   naemon.spec

cd naemon-core && ./update-version "$1" "$DATE"
